---
title: "Gender vs Percieved Gender"
author: "Alexander Porshnev"
date: "2023-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis')
library(data.table)
library(knitr)
```

```{r}
path = "C:\\Alex\\Maynooth\\IAT\\Gender-Career\\Analysis\\Sep23_stage2_All_years\\Clean_datasets\\"
years = 2005:2006
i=2020

for (i in 2016:2017)
{
  p_data<-fread(paste0(path, "p_", i, ".csv"))
  table(p_data$sex)
  table(p_data$genderidentity)
  table(p_data$birthsex)
  
}

years_to_load<-c(2016:2017)

init_dir <- "C:\\Alex\\Maynooth\\IAT\\Gender-Career\\source_Datasets\\" 
i=2017

p_data_files<-NULL
for (i in years_to_load){
  p_data_files<- paste0(init_dir, "Gender-Career IAT.public.", i, "-CSV/Gender-Career IAT.public.", i, ".csv")
  cat(paste0("\n# ", i,"\n"))
  p_data<-fread(p_data_files[1])
  print(kable(table(p_data$sex), caption = "Variable sex"))
  print(kable(table(p_data$genderidentity), caption = "Variable gender identity"))
  print(kable(table(p_data$birthsex), caption = "Variable birth sex"))
  cat("\n## Conclusion \n")
  gi_male<-table(p_data$genderidentity)[names(table(p_data$genderidentity))=="[1]"]
  bs_male<-table(p_data$birthsex)[1]
  cat(paste0("Percent of participant with birthsex - male and gender identity male ",
               round(gi_male/bs_male,3),
               " with different identity:",
               round(bs_male-gi_male,3), " out of ", bs_male, "\n"
               ), sep = "\n")
  gi_female<-table(p_data$genderidentity)[names(table(p_data$genderidentity))=="[2]"]
  bs_female<-table(p_data$birthsex)[2]
  
  cat(paste0("Percent of participant with birthsex - female and gender identity female ",
               round(gi_female/bs_female,3),
               " with different identity:",
               round(bs_female-gi_female,3), " out of ", bs_female, "\n"
               ), sep = "\n")
  
  }


years_to_load<-c(2018:2021)

init_dir <- "C:\\Alex\\Maynooth\\IAT\\Gender-Career\\source_Datasets\\" 

#names(p_data)

for (i in years_to_load){
  p_data_files<- paste0(init_dir, "Gender-Career IAT.public.", i, "-CSV/Gender-Career IAT.public.", i, ".csv")
  cat(paste0("\n# ", i,"\n"))
  p_data<-fread(p_data_files)
  #print(kable(table(p_data$sex), caption = "Variable sex"))
  print(kable(table(p_data$genderIdentity), caption = "Variable gender identity"))
  print(kable(table(p_data$birthSex), caption = "Variable birth sex"))
  cat("\n## Conclusion \n")
  gi_male<-table(p_data$genderIdentity)[names(table(p_data$genderIdentity))=="[1]"]
  bs_male<-table(p_data$birthSex)[1]
  cat(paste0("Percent of participant with birthsex - male and gender identity male ",
               round(gi_male/bs_male,3),
               " with different identity:",
               round(bs_male-gi_male,3), " out of ", bs_male, "\n"
               ), sep = "\n")
  gi_female<-table(p_data$genderIdentity)[names(table(p_data$genderIdentity))=="[2]"]
  bs_female<-table(p_data$birthSex)[2]
  cat(paste0("Percent of participant with birthsex - female and gender identity female ",
               round(gi_female/bs_female,3),
               " with different identity:",
               round(bs_female-gi_female,3), " out of ", bs_female, "\n"
               ), sep = "\n")   
}
```

