---
title: "participants_and_user_ids"
author: "Alexander Porshnev"
date: "2023-09-15"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, results = 'asis')
library(data.table)
library(dplyr)
library(knitr)

```
# Important NOTE:

Analysis of previous_session_ids and user_ids based on results from 

https://github.com/aporshnev/iat_gender_career/blob/main/user_id.py

https://github.com/aporshnev/iat_gender_career/blob/main/participant_id.py

so participants_ids.csv

session_count.csv

user_ids.csv - needed to be calculated from clean data


```{r}
df_part <- fread("C:\\Alex\\Maynooth\\IAT\\Gender-Career\\Datasets\\RAW_Preprocessed\\Clean_datasets\\participants_ids.csv", sep = ";")
#names(df_part)
kable(table(df_part$V3), caption = "Number of participand by number of repetitions of G&C studies in 15 minutes frame") 

df_other_studies <- fread("C:\\Alex\\Maynooth\\IAT\\Gender-Career\\Datasets\\RAW_Preprocessed\\Clean_datasets\\participants_ids_other_iat_studies.csv", sep = ";")
#names(df_other_studies)

kable(table(df_other_studies$V3), caption = paste0("Number of participand who participated in other IAT studies in 15 minutes time frame - ", length(df_other_studies$V3))) 

df_user <- fread("C:\\Alex\\Maynooth\\IAT\\Gender-Career\\Datasets\\RAW_Preprocessed\\Clean_datasets\\user_ids.csv", sep = ";")
names(df_user)
kable(table(df_user$V2), caption = "Distribution of registred users by number of G&C experiments they took part")

main_user<-filter(df_user, V2>1)
df_sess <- fread("C:\\Alex\\Maynooth\\IAT\\Gender-Career\\Datasets\\RAW_Preprocessed\\Clean_datasets\\session_count.csv", sep = ";")
#names(df_sess)
#head(df_sess)

df_sess_more2<-filter(df_sess, V3 %in% main_user$V1)

kable(head(table(df_sess_more2$V3, df_sess_more2$V4)), caption = "Example of the data from participants who took part several times")

check_years<-as.matrix(table(df_sess_more2$V3, df_sess_more2$V4))

user_list=NULL
for (i in (1:length(check_years[,1]))){
  count=0
  for(j in (1:17)){
    if (check_years[i,j]>0) 
    {count=count+1
      if (count>1){ 
        user_list<-c(user_list, rownames(check_years)[i])
      }
    }
  }
}
print(paste0("Found ", length(user_list), " participants who took part in experiment in different years"))

df_sess_more3<-filter(df_sess, V3 %in% user_list)

kable(table(df_sess_more3$V3, df_sess_more3$V4), caption = "Ids of participants who took part in experiment in different years")

```

