---
title: "Gender&Career IAT Analysis"
author: "Alexander Porshnev"
date: "2023-08-28"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results='asis')
library(dplyr)
library(knitr)
library(psych)
library(md.log)
library(data.table)
```

# Gender & Career experiment  IAT 2005-2022 (https://osf.io/abxq7/)

IAT task:
  
Female stimuli are: Rebecca, Michelle, Emily, Julia, Anna

Male stimuli are: Ben, Paul, Daniel, John, Jeffrey

Career stimuli are: Career, Corporation, Salary, Office, Professional, Management, Business

Family stimuli are: Wedding, Marriage, Parents, Relatives, Family, Home, Children

```{r d-calculations, results='asis'}
d_calculations<- function(block1, block2){

res1 <- t_data %>% filter(block_number %in% block1) %>% group_by(session_id) %>% summarize(M_block1 = mean(trial_latency), )
res2 <- t_data %>% filter(block_number %in% block2) %>% group_by(session_id) %>% summarize(M_block2 = mean(trial_latency), )
res12sd <- t_data %>% filter(block_number %in% c(block1, block2)) %>% group_by(session_id) %>% summarize(sd12 = sd(trial_latency))

by = join_by(session_id)
check_data<-left_join(res1, res2, by)
check_data<-left_join(check_data, res12sd, by)
check_data$D<-(check_data$M_block1-check_data$M_block2)/(check_data$sd12)
p_data$order_sign<- ifelse(p_data$Order==2,1,-1)

check_data_res<-left_join(p_data[,c("session_id", "order_sign" )], check_data[,c("D", "session_id")], by)
check_data_res$D<-check_data_res$D*check_data_res$order_sign

return (check_data_res[,c(1,3)])
}
```

```{r d-mean calculations, results='asis'}
d_mean<-function(name){
    if (as.numeric(name)>2016){
       d1 <- d_calculations(c(3), c(6))
       d2 <- d_calculations(c(4), c(7))
    }
    else{
       d1 <- d_calculations(c(2), c(5))
       d2 <- d_calculations(c(3), c(6))    
  }
  
  check_data_res<-left_join(d1, d2, by = "session_id")
  check_data_res$D_mean<-(check_data_res$D.x+check_data_res$D.y)/2
  
  return (check_data_res[,c(1,4)])
}
```


```{r describe dataset, results = 'asis'}
describe_dataset<-function(name){
  if (as.numeric(name)>2016){
    #name<-2017
    #block1<-c(2,3)
    #block2<-c(5,6)
    print(paste0("Dataset from:", name))
    p_data$countryres<-NA
    p_data$countryres[p_data$countryres_num==1] <- "US"
    p_data$countryres[p_data$countryres_num==225] <- "UK"
    if (as.numeric(name)>2017){
      p_data$sex<-NA
      p_data$sex[p_data$birthSex==1]<-"m"
      p_data$sex[p_data$birthSex==2]<-"f"
    }
    else{
      p_data$sex<-NA
      p_data$sex[p_data$birthsex==1]<-"m"
      p_data$sex[p_data$birthsex==2]<-"f"    
    }
  
    p_data$age <- as.numeric(name)-p_data$birthyear
  }
  
  p_clean <- p_data %>% filter((countryres=="US" | countryres=="UK" )
                               & !is.na(D_biep.Male_Career_all)
                               & sex %in% c("m","f")
                               & age>17)
  print(kable(table(p_clean$countryres==p_clean$countrycit), caption = "Country of residence = Country of origin"))
  print(kable(table(p_clean$sex), caption = "Disrtibution by birthsex"))
  print(kable(table(p_clean$politicalid_7), caption = "Distribution by Political values"))
  print(kable(describe(p_clean$age)))
  d_m <- d_mean(name)
  #d_m<- d_calculations(c(3,4), c(6,7))
  
  d_check<-left_join(p_clean[,c("session_id", "D_biep.Male_Career_all", "countryres")], d_m, by = "session_id")
  
  print(kable(head(d_check), caption = "D check"))
  
  print(kable(table(d_check$countryres, (d_check$D_biep.Male_Career_all-d_check$D_mean)<0.001), caption = "Results of D-calculations"))
  clean_ids<- d_check$session_id[(d_check$D_biep.Male_Career_all-d_check$D_mean)<0.001 & !is.na(d_check$D_mean)]
  
  print(kable(table(!is.na(p_clean$previous_session_id), p_clean$countryres), caption = "Previous sessions count"))
  
  print(paste0("Participated in the ", name, " year"))
  print(sum(p_clean$previous_session_id %in% p_clean$session_id ))
  
  p_clean <- p_clean%>%filter(session_id %in% clean_ids)
  
  md.log("writing clean participants file")
  fwrite(p_clean, file = paste0("Clean_datasets/p_", name, ".csv"), append = FALSE, sep = ";")
  md.log("Done")
  md.log("writing trial file")
  t_clean <- t_data %>% filter (session_id %in% clean_ids)
  fwrite(t_clean, file = paste0("Clean_datasets/t_", name, ".csv"), append = FALSE, sep = ";")
  md.log("Done")
}
```

# Datasets & Variables
```{r main, results='asis'}
#sav file variables have problems, like "UK    " , so we will use year by year data

md.log("Start", file = "log.txt", append = FALSE)

years_to_load<-c(2005:2021)

init_dir <- getwd() 

raw_data_dir<-paste0(getwd(), "/GenderCareer_iat_", years_to_load)
p_data_files<-NULL
for (i in years_to_load){
  p_data_files<-c(p_data_files, paste0(getwd(), "/Gender-Career IAT.public.", i, "-CSV/Gender-Career IAT.public.", i, ".csv"))
}
i=1
for (i in c(1:length(years_to_load))){
  data_files<-list.files(raw_data_dir[i])
  data_files<-data_files[grep("*.txt$",data_files)]
  data_files<-paste0(raw_data_dir[i],"/", data_files)
  md.log(years_to_load[i])
  data_from_year<-NULL
  for (j in data_files){
    #d<-read.csv(j, header = TRUE, sep = "\t")
    d<-fread(j, header = TRUE, sep = "\t")
    md.log(j)
    data_from_year<-rbind(data_from_year, d)    
  }
  t_data<-data_from_year
  md.log("Data uploaded")
  #names(p_data)
  
  p_data <- fread(p_data_files[i], header = TRUE, sep =",")
  p_data$se
  print(years_to_load[i])
  md.log("Start  analyzing year data")
  describe_dataset(years_to_load[i])
  md.log("Year described")
}


```