---
title: "Step 01. Cleaning_raw_data"
author: "Alexander Porshnev"
date: "2023-10-27"
output: html_document
---

```{r setup, include=FALSE}
# Main data preprocessing

knitr::opts_chunk$set(echo = FALSE, results = 'asis', warning = FALSE)
library(dplyr)
library(knitr)
library(psych)
library(md.log)
library(data.table)
library(tidyr)
```


```{r}
year<-2005
path_data= "C:/Alex/Maynooth/IAT/Gender-Career/Analysis/git_for_replication/iat_gender_career/"
path = getwd()

t_prev_year_check<-NULL

preprocess<-function(year, t_prev_year_check){
stats<-NULL
stats<-cbind(stats, year = year)
#setwd("..")
#path<-getwd()
init_dir <-paste0(path_data, "in_RAW_IAT_data") # "../../source_Datasets" 
p_data_files<- paste0(init_dir, "/Gender-Career IAT.public.", year, "-CSV/Gender-Career IAT.public.", year, ".csv") 

init_dir_sample <-paste0(path_data, "sample_RAW_IAT_data") # "../../source_Datasets" 
dir.create(init_dir_sample)
p_data_dir_sample<- paste0(init_dir_sample, "/Gender-Career IAT.public.", year, "-CSV/")
#Gender-Career IAT.public.", year, ".csv") 
dir.create(p_data_dir_sample)
p_data_files_sample<- paste0(init_dir_sample, "/Gender-Career IAT.public.", year, "-CSV/Gender-Career IAT.public.", year, ".csv") 

p_data <- fread(p_data_files, header = TRUE, sep =",", colClasses=c("session_id" = "character")) # participant level data

stats<-cbind(stats, total = length(unique(p_data$session_id)))


raw_data_dir<-paste0(path_data, "/in_RAW_IAT_data/GenderCareer_iat_", year)

raw_data_sample<-paste0(init_dir_sample, "/GenderCareer_iat_", year)
dir.create(raw_data_sample)
t_data_files_sample<-paste0(raw_data_sample, "/iat.txt")

data_files<-list.files(raw_data_dir)
data_files<-data_files[grep("*.txt$",data_files)]
data_files<-paste0(raw_data_dir,"/", data_files)

jan_01_data<- p_data %>% filter(month==1 & day == 1)


#md.log(years_to_load[year])
if (!is.null(t_prev_year_check)) {
  data_from_year<-t_prev_year_check %>% filter(session_id %in% jan_01_data$session_id) 
  cat(paste0("\n Found in previous year = ", length(unique(data_from_year$session_id))))
  stats<-cbind(stats, add_from_prev_year = length(unique(data_from_year$session_id)))
} else {
  try(t_prev_year_check<-fread(file= paste0("/IAT_sample/stats/t_prev", year-1, ".csv"), colClasses=c("session_id" = "character")))
 
   if (!is.null(t_prev_year_check)) {
  data_from_year<-t_prev_year_check %>% filter(session_id %in% jan_01_data$session_id) 
  cat(paste0("\n Found in previous year = ", length(unique(data_from_year$session_id))))
  stats<-cbind(stats, add_from_prev_year = length(unique(data_from_year$session_id)))
   }
  else{
 data_from_year<-NULL
 stats<-cbind(stats, add_from_prev_year = 0)
 cat("\n No data from previous year found")
  }
}

for (j in data_files){
    d<-fread(j, header = TRUE, sep = "\t", colClasses=c("session_id" = "character"))
    data_from_year<-rbind(data_from_year, d)    
  }

t_data<-data_from_year # trial level data

t_data_no_dpl <- t_data %>% distinct(trial_number, trial_name, trial_latency, session_id, block_number, .keep_all = TRUE) 

cat(paste0("\n# ", year, "\n"))

cat(paste0("\n In trial dataset from:", year, " = ", nrow(t_data), " after removing trial duplicates we keep = ", nrow(t_data_no_dpl),"\n"))

t_data<-t_data_no_dpl

rm(t_data_no_dpl)
rm(d)
rm(data_from_year)

t_prev_year_check<-t_data%>% filter(!(session_id %in% p_data$session_id))

nrow(p_data)
  p_data<-sample_n(p_data, size = 1000, replace = FALSE)

  t_data<- t_data %>% filter(session_id %in% p_data$session_id)

fwrite(t_data, file= t_data_files_sample, sep = "\t")
fwrite(p_data, file= p_data_files_sample)
fwrite(stats, file= paste0(path, "/IAT_sample/stats/stats_", year, ".csv"))
fwrite(t_prev_year_check, file= paste0(path, "/IAT_sample/stats/t_prev", year, ".csv"))
prev_stats<-NULL

try(prev_stats<-fread(file= paste0(path, "/IAT_sample/stats/res_stats_", year-1, ".csv")))
if (!is.null(prev_stats)) {
  stats <- rbind(prev_stats, stats)
}
fwrite(stats, file= paste0(path, "/IAT_sample/stats/res_stats_", year, ".csv"))
gc()
return (t_prev_year_check)
}
```
 
 
```{r}
md.log("Start sampling", file="log_sampling.log", append =FALSE, time = TRUE, sys.info = FALSE)
t_prev <- NULL
i<-2005
for(i in 2005:2021)
{
  md.log("------------")
  md.log(paste0(i, "year started"))
  t_prev <- preprocess(i, t_prev)
  md.log(paste0("year completed"))

}
```
 
 