---
title: "LDM analysis report"
author: "Alexander Porshnev"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis', warning = FALSE)  

library(dplyr)
library(data.table)
library(lme4)
library(flexmix) #for BIC
library(sjPlot)
library(knitr)
library(stringr)
library(performance)
library(md.log)
library(psych) # needed for cor.ci
library(tidyr)




```

```{r functions}
lm_model<-function(formula, lm = TRUE,  data){
if (lm == TRUE){
  r_model<-lm(formula, data) # simple model
}
else{
  r_model<-lmer(formula, data, REML = TRUE ) # random effect model  
}
cat(paste0("\n#### Model:   ",formula, "\n"))
BIC_r_model <- round(BIC(r_model),2)
cat(paste0("\n#### BIC: ",BIC_r_model, "\n\n\n"))

return (r_model)
}

corpora_from_baseline <- function(baseline_formula){
  corpora_name<-NULL
  if (grepl("logUKWAC",baseline_formula)>0) {
    return ("ukwac")}
  if (grepl("logSUBTITLES",baseline_formula)>0) {
    return ("subtitles")}
  if (grepl("logBNC",baseline_formula)>0) {
    return("bnc")}

    return ("na")
}


add_feature<-function(fname, baseline, name_in_func, regression_type = TRUE, sample_name, model_type)
{
  name_in_func<-name
  feature_data<-fread(fname)
  
  try(names(feature_data)<- c("n","First.word", "Second.word", name_in_func))
  try(names(feature_data)<- c("First.word", "Second.word", name_in_func))
  #[TBD] create unified output for open and custom models on step 3 or 4?
  
  feature_data$First.word <- tolower(feature_data$First.word)
  feature_data$stimuli<-paste0(feature_data$First.word,"_", feature_data$Second.word)
  
  female <- tolower(c("Rebecca", "Michelle", "Emily", "Julia", "Anna"))
  male <- tolower(c("Ben", "Paul", "Daniel", "John", "Jeffrey"))
  career<-tolower(c("Career", "Corporation", "Salary", "Office", "Professional", "Management", "Business"))
  family<-tolower(c("Wedding", "Marriage", "Parents", "Relatives", "Family", "Home", "Children"))

  RT_data$trial_response<-NA
  
  RT_data$trial_response <- ifelse(RT_data$congruent & RT_data$stimuli %in% female, "family",
                                   ifelse(!RT_data$congruent & RT_data$stimuli %in% female, "career",
                                   ifelse(RT_data$congruent & RT_data$stimuli %in% male, "career",
                                   ifelse(!RT_data$congruent & RT_data$stimuli %in% male, "family",
                                   ifelse(!RT_data$congruent & RT_data$stimuli %in% career, "female",
                                   ifelse(RT_data$congruent & RT_data$stimuli %in% career, "male",
                                   ifelse(!RT_data$congruent & RT_data$stimuli %in% family, "male",
                                   ifelse(RT_data$congruent & RT_data$stimuli %in% family, "female",
                                          0))))))))
  
  RT_data$stimuli_join<-paste0(RT_data$stimuli, "_", RT_data$trial_response)

  RT_data_use<-left_join(RT_data, feature_data, by = join_by("stimuli_join"== "stimuli", ))
  cor_data<-RT_data_use %>% select(c("m_RT", "congruent", "Letters_n", "Syllables_n", "logUKWAC", "logBBC", "logBNC", name_in_func ))
  RT_data_use$logSUBTITLES<-RT_data_use$logBBC

  #cor_data$congruent<-cor_data$congruent*1
  cor_table<-stats::cor(cor_data)
  
  cor_CI<-cor.ci(cor_data, plot = FALSE)
  
  cor_LDM<-stats::cor(cor_data$m_RT, cor_data[,8])
  cor_LDM_CI_lower<-cor_CI$ci$lower[7]
  cor_LDM_CI_upper<-cor_CI$ci$upper[7]
  
  cor_congruent<-stats::cor(cor_data$congruent, cor_data[,8])
  
  print("EX1")
  print(kable(cor_table)) 
  b_model<-lm_model(baseline, regression_type,  RT_data_use)
#names(RT_data_use)[names(RT_data_use)==name_in_func]<-name
  f <- paste0(baseline, paste0(" + ", name_in_func))
  res<-lm_model(f,regression_type, RT_data_use)  
  
  ##Comparison baseline with LDM
  
  #file_tab_model = paste0(path, "/Step_04/out_4_Models_",model_type,"/", sample_name,"_", name_in_func,  "_", corpora_from_baseline(baseline), ".html")
  #print(tab_model(b_model, res, file = file_tab_model))
  #md.log(paste0(file_tab_model, "- saved"))
  
  ## Formating for nice output in html 
  #cat(tab$page.style)
  #cat(tab$page.content)
 
 # f_congr <- paste0(baseline, paste0(" + ", name_in_func, "+ congruent"))
#  res_congr<-lm_model(f_congr,regression_type, RT_data_use)  
  
  ##Comparison LDM and LDM with congruency
  #file_tab_model = paste0(path,"/Step_04/out_4_Models_",model_type,"/",sample_name, "_", name_in_func, "_", corpora_from_baseline(baseline), "_congruent.html")
  #print(tab_model(res, res_congr, file = file_tab_model))
  #md.log(paste0(file_tab_model, "- saved"))
  

  compare <- anova(b_model, res)
  print(kable(compare, caption = "Baseline vs LDM feature"))
  #cat("\\n### VIF analysis: VIF value greater than 1.5 indicates multicollinearity")
  #print(kable(car::vif(res)))


  
  if (regression_type == FALSE) {
  pv = round(compare$`Pr(>F)`[2],3)
        r<-summary(res)
        coef<-round(r$coefficients[5,1],2)[[1]]
    out_result<- c(lmd = name_in_func, baseline = baseline,
                 corLDMmRT = round(cor_LDM,3), 
                 corLDMmRT_CI_lower = round(cor_LDM_CI_lower,3), 
                 corLDMmRT_CI_upper = round(cor_LDM_CI_upper,3), 
                 corLDM_congruent = cor_congruent, 
                 coef = coef,  
                 p_value = pv, 
                 BIC = round(BIC(res),1))
  }
  else{
    coef = round(res$coefficients[name_in_func],2)[[1]]
    pv = round(compare$`Pr(>F)`[2],3)
    out_result<- c(lmd = name_in_func, baseline = baseline,
                 corLDMmRT = round(cor_LDM,3), 
                 corLDMmRT_CI_lower = round(cor_LDM_CI_lower,3), 
                 corLDMmRT_CI_upper = round(cor_LDM_CI_upper,3), 
                 corLDM_congruent = cor_congruent, 
                 "coef" = coef,  
                 p_value = pv, BIC = round(BIC(res),1))}

  return (out_result)
}  
```



## LDM features vs baseline model BNC

```{r main}
md.log("Start","Step_04_log.txt", append = FALSE)

dir_structure<-c(paste0("Step_04/out_4_Models_",model_type, "/"),
                 paste0("Step_04/out_4_Summary_",model_type, "/"),
                 paste0("Step_04/out_4_Models_", model_type, "/", start_year,"-", finish_year,"/"),
                paste0("Step_04/out_4_Summary_", model_type, "/", start_year,"-", finish_year,"/"))

for (d in dir_structure){
dir.create(file.path(path, d), showWarnings = FALSE)
}
md.log("Directory created")
md.log(path)
md.log(dir_structure)
       
corpora_name<-c("subtitles", "bnc", "ukwac")
init<-NULL
j<-1
#setwd("..")
#path = getwd()
#path<-"C:/Alex/Maynooth/IAT/Gender-Career/Analysis/git_for_replication/iat_gender_career"

for (j in 1:3)
  {
  init<-rbind(init,
               c(path =paste0(path, "/in_Distances/n-gram/"),
                   pattern = paste0("", corpora_name[j]),
                 freq = paste0("log", toupper(corpora_name[j])))
              ,
              c(path =paste0(path,"/in_Distances/Cosine/"),
               pattern=paste0("cos_", corpora_name[j]),
               freq = paste0("log", toupper(corpora_name[j]))
               ),

               c(path =paste0(path,"/in_Distances/Euclidean/"),
                 pattern=paste0("euc_", corpora_name[j]),
                 freq = paste0("log", toupper(corpora_name[j]))
                 ),
               c(path =paste0(path,"/in_Distances/Correlation/"),
                   pattern = paste0("cor_", corpora_name[j]),
                   freq = paste0("log", toupper(corpora_name[j]))
                 ),
               c(path =paste0(path,"/in_Distances/llms_systematic/"),
                  pattern = paste0(".csv"),
                  freq = paste0("log", toupper(corpora_name[j])))
               ,
               c(path =paste0(path,"/in_Distances/GloVe_distances/"),
                 pattern = paste0(".csv"),
                   freq = paste0("log", toupper(corpora_name[j])))
            )
  
}

i=1

sample_name="A"
#from all_steps parameter list: model_type<-"classic" 

for (sample_name in c("A", "B")){
  out<-NULL
  RT_data<-fread(paste0(path, "/Step_03/out_3_EXT_RT/",start_year,"-", finish_year,"/RT_",start_year,"_", finish_year,"_extended_", sample_name, ".csv"))
  for (i in 1:length(init[,1])){
    cor_files<-list.files(init[i,1], init[i,2], all.files=FALSE, include.dirs = FALSE, full.names=FALSE)
    features_data<-paste0(init[i,1], cor_files) 
    f_files<-t(as.data.frame(str_split(features_data, "[/]"))[8,])
    rownames(f_files)<-NULL
    colnames(f_files)<-"Filename"
    cat(paste0("\n\n\n### Files for   ",init[i,2], "\n"))
    print(kable(f_files), caption = "Features list")
    j=features_data[1]
    for (j in features_data){
      s_name<-unlist(str_split(j, "/"))
      ldm_name<-(s_name[length(s_name)])
      cat(paste0("\n\n\n### LDM_feature:   ",ldm_name, "\n"))
      name<-gsub(".csv", "", ldm_name)
      name<-gsub("[-]", "_", name) # need because of - and . in names of llms [TBD] [-.]
      name<-gsub("[.]", "_", name)
      md.log(paste0(name, " - started"))
      
      if (model_type=="classic"){
        baseline_formula <-  paste0("m_RT ~ country + Letters_n + Syllables_n+ ", init[i,3])}
      if (model_type=="simple"){
        baseline_formula <-  paste0("m_RT ~ country +  Letters_n + ", init[i,3])}
      if (model_type=="mixed"){
        baseline_formula <-  paste0("m_RT ~  (1|stimuli) + country +  Letters_n+", init[i,3])}

      #classic:  paste0("m_RT ~ country + Letters_n + Syllables_n+ ", init[i,3])
      #simple:  paste0("m_RT ~ country +  Letters_n + ", init[i,3])
      #mixed: paste0("m_RT ~  (1|stimuli) + country +  Letters_n+", init[i,3])
      #tryCatch(
      add_feature(j, baseline_formula, name, regression_type = TRUE, sample_name, model_type)
      out<-rbind(out, add_feature(j, baseline_formula, name, regression_type = TRUE, sample_name, model_type))
      #), error = function(e){ md.log("failed")})
        md.log(" -- done -- ")
    }
}

fwrite(out, paste0(path,"/Step_04/out_4_Summary_", model_type,"/",start_year,"-", finish_year,"/Summary_table_",start_year,"_", finish_year,"_" ,sample_name, "_", model_type,".csv"))
#mmb - for mixed models baseline  m_RT ~  (1|stimuli) + country +  Letters_n
}

```

